VERSION 0.7
FROM node:18

deps:
    COPY ./package*.json ./
    RUN npm install
    # Output these back in case npm install changes them.
    SAVE ARTIFACT package.json AS LOCAL ./app/package.json

generate-client-axios:
    FROM earthly/dind:alpine
    COPY ../backend/+generate-client-spec/* /
    WORKDIR stage
    WITH DOCKER --pull openapitools/openapi-generator-cli:v6.6.0
        RUN docker run -v $(pwd):/tmp/client -v /openapi.json:/openapi.json openapitools/openapi-generator-cli:v6.6.0 generate -i /openapi.json -g typescript-axios -o /tmp/client --additional-properties=withSeparateModelsAndApi=true,apiPackage=api,modelPackage=model
    END
    SAVE ARTIFACT ./* AS LOCAL ./src/client/
    

build:
    FROM +deps
    COPY --dir ./src ./src
    COPY vite.config.ts tsconfig.* *.config.js index.html ./
    RUN MYCELIUM_HOST=https://mycelium.fly.dev npm run build
    SAVE ARTIFACT dist AS LOCAL ./dist