# fly.toml app configuration file generated for mycelium on 2023-07-07T07:53:49+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mycelium"
primary_region = "fra"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PG_HOST = "ep-super-limit-61125340.eu-central-1.aws.neon.tech"
  PG_USER = "av3ng3r"
  PG_DB = "neondb"
  S3_HOST = ""
  S3_ACCESS_KEY = ""
  SENTRY_BACKEND_DSN = "https://c80d0d99dc464a3b899c5d06b0a06cf3@o4505515472977920.ingest.sentry.io/4505515475009536"