# fly.toml app configuration file generated for mycelium on 2023-07-07T07:53:49+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mycelium"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PG_HOST = "little-flower-9130.internal"
  PG_USER = "postgres"
  PG_DB = "postgres"
  S3_HOST = ""
  S3_ACCESS_KEY = ""