version: "2"
services:
  influxdb:
    image: influxdb:2.0
    environment:
      DOCKER_INFLUXDB_INIT_ORG: "mycelium"
      DOCKER_INFLUXDB_INIT_BUCKET: "mycelium"
      DOCKER_INFLUXDB_INIT_USERNAME: "mycelium"
      DOCKER_INFLUXDB_INIT_PASSWORD: "a2122dc0a12140857f772e1f"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "a2122dc0a12140857f772e1f"
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_RETENTION: "52w"
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./conf/influxdb:/etc/influxdb/
    restart: always

  s3:
    image: minio/minio
    volumes:
      - ./data:/data
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniominio
    ports:
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  db:
    image: mdillon/postgis:11-alpine
    restart: always
    volumes:
      - ./pg/backup:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mycelium
      POSTGRES_USER: mycelium
      POSTGRES_PASSWORD: mycelium
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mycelium"]
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 30