VERSION 0.7
FROM sbtscala/scala-sbt:eclipse-temurin-jammy-11.0.17_8_1.9.2_2.13.11

deps:
    COPY build.sbt ./
    COPY --dir project project
    RUN sbt update

build:
    FROM +deps
    COPY --dir src src
    RUN sbt assembly
    SAVE ARTIFACT target/scala-2.13 bin AS LOCAL build/bin

dev:
    FROM eclipse-temurin:17.0.7_7-jre
    COPY +build/bin build/bin
    ENTRYPOINT ["java","-cp","build/bin/backend-assembly-1.0.jar","co.mycelium.Main"]
    SAVE IMAGE local/project-mycelium-backend:dev


stage:
    FROM eclipse-temurin:17.0.7_7-jre
    COPY +build/bin build/bin
    COPY ../frontend+build/* ./
    ENTRYPOINT ["java","-cp","build/bin/backend-assembly-1.0.jar","co.mycelium.Main"]
    SAVE IMAGE local/project-mycelium-backend:dev

generate-client-spec:
    FROM +deps
    COPY --dir src src
    RUN sbt "runMain co.mycelium.OpenApiGenerator"
    SAVE ARTIFACT openapi.json AS LOCAL openapi

docker:
    FROM eclipse-temurin:17.0.7_7-jre
    COPY +build/bin build/bin
    COPY ../frontend+build/* ./
    ARG EARTHLY_GIT_HASH
    ENTRYPOINT ["java","-cp","build/bin/backend-assembly-1.0.jar","co.mycelium.Main"]
    SAVE IMAGE --push ghcr.io/fristi/project-mycelium-backend:$EARTHLY_GIT_HASH