VERSION 0.7
FROM sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.8.2_2.13.10

deps:
    COPY build.sbt ./
    COPY --dir project project
    RUN sbt update

build:
    FROM +deps
    COPY --dir src src
    RUN sbt assembly
    SAVE ARTIFACT target/scala-2.13 bin AS LOCAL build/bin

docker:
    COPY +build/bin build/bin
    ARG EARTHLY_GIT_SHORT_HASH
    ENTRYPOINT ["java","-cp","build/bin/scala-example-assembly-1.0.jar","Main"]
    SAVE IMAGE --push ghcr.io/fristi/project-mycelium-backend:$EARTHLY_GIT_SHORT_HASH