VERSION 0.7
FROM sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.8.2_2.13.10

deps:
    COPY build.sbt ./
    COPY --dir project project
    RUN sbt update

build:
    FROM +deps
    COPY --dir src src
    RUN sbt assembly
    SAVE ARTIFACT target/scala-2.13 bin AS LOCAL build/bin

docker:
    FROM eclipse-temurin:17.0.7_7-jre
    COPY +build/bin build/bin
    COPY ../frontend+build/* ./
    ARG EARTHLY_GIT_SHORT_HASH
    ENTRYPOINT ["java","-cp","build/bin/backend-assembly-1.0.jar","co.mycelium.Main"]
    SAVE IMAGE --push ghcr.io/fristi/project-mycelium-backend:$EARTHLY_GIT_SHORT_HASH

deploy:
    FROM flyio/flyctl
    ARG EARTHLY_GIT_SHORT_HASH
    RUN sleep 60
    RUN --secret FLY_API_TOKEN flyctl deploy --image ghcr.io/fristi/project-mycelium-backend:$EARTHLY_GIT_SHORT_HASH