CREATE TABLE plant_details (
    id serial PRIMARY KEY,
    common_name text NOT NULL,
    scientific_name text[] NOT NULL,
    other_name text[] NOT NULL,
    family text,
    origin text[] NOT NULL,
    type text NOT NULL,
    dimension text NOT NULL,
    cycle text NOT NULL,
    propagation text[] NOT NULL,
    watering text NOT NULL,
    watering_period text,
    sunlight text[] NOT NULL,
    pruning_month text[] NOT NULL,
    seeds integer NOT NULL,
    maintenance text,
    soil text[] NOT NULL,
    growth_rate text NOT NULL,
    drought_tolerant boolean NOT NULL,
    salt_tolerant boolean NOT NULL,
    thorny boolean NOT NULL,
    invasive boolean NOT NULL,
    tropical boolean NOT NULL,
    indoor boolean NOT NULL,
    care_level text,
    pest_susceptibility text[] NOT NULL,
    pest_susceptibility_api text NOT NULL,
    flowers boolean NOT NULL,
    flowering_season text,
    flower_color text NOT NULL,
    cones boolean NOT NULL,
    fruits boolean NOT NULL,
    edible_fruit boolean NOT NULL,
    edible_fruit_taste_profile text NOT NULL,
    fruit_nutritional_value text NOT NULL,
    fruit_color text[] NOT NULL,
    harvest_season text,
    leaf boolean NOT NULL,
    leaf_color text[] NOT NULL,
    edible_leaf boolean NOT NULL,
    cuisine boolean NOT NULL,
    medicinal boolean NOT NULL,
    poisonous_to_humans integer NOT NULL,
    poisonous_to_pets integer NOT NULL,
    description text NOT NULL
);