# This Earthfile aims to build Rust for the ESP32 microcontrollers.
# Makes use of the well tested scripted install from the Rust ESP comunity:
# https://github.com/esp-rs/rust-build
VERSION 0.7
FROM debian:stable-slim

linux-setup:
  RUN apt update && apt-get install -y git curl gcc wget flex bison gperf python3 python3-pip python3-virtualenv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0 unzip

esp-rust-setup:
  FROM +linux-setup
  GIT CLONE --branch build/1.70.0.1 https://github.com/esp-rs/rust-build.git rust-build
  WORKDIR rust-build
  RUN ./install-rust-toolchain.sh --llvm-version esp-15.0.0-20221014 --build-target esp32 --extra-crates "ldproxy"
  SAVE ARTIFACT /root/.espressif/* ./espressif

build:
  FROM +esp-rust-setup
  WORKDIR build
  
  # Build type, default is debug. 
  # can be overridden on the command line via "--build-arg BUILD_TYPE=release" to get a release build.
  ARG BUILD_TYPE

  COPY +esp-rust-setup/espressif /root/.espressif

  # RUN ls /root/.espressif/tools/xtensa-esp32-elf-clang/esp-15.0.0-20221014-x86_64-unknown-linux-gnu
  # RUN ls /root/.espressif/tools/xtensa-esp32-elf-clang/esp-15.0.0-20221014-x86_64-unknown-linux-gnu/esp-clang
  # RUN ls /root/.espressif/tools/xtensa-esp32-elf-clang/esp-15.0.0-20221014-x86_64-unknown-linux-gnu/esp-clang/lib
  # RUN false

  # /root/.espressif/tools/xtensa-esp32-elf-clang/esp-15.0.0-20221014-x86_64-unknown-linux-gnu/esp-clang/lib/
  # /root/.espressif/tools/xtensa-esp32-elf-clang/esp-15.0.0-20221014-x86_64-unknown-linux-gnu

  # These vaules are emited after installing the toolchain.
  # There is no way yet to get this progamaticly, thus this will need updating at times when build tooling updates.
  ENV PATH="/root/.cargo/bin:/root/.espressif/tools/xtensa-esp32-elf-clang/esp-15.0.0-20221014-$TARGETARCH-unknown-linux-gnu/bin/:$PATH"
  ENV LIBCLANG_PATH="/root/.espressif/tools/xtensa-esp32-elf-clang/esp-15.0.0-20221014-$TARGETARCH-unknown-linux-gnu/esp-clang/lib"

  COPY . .
  # Set Rust to use ESP as the default toolchain
  RUN rustup default esp
  
  # What type of build, default is debug.
  IF [ "$BUILD_TYPE" = "release" ]
    RUN echo "[INFO] Building a release binary"
    RUN cargo +esp build --target xtensa-esp32-espidf --release
  ELSE
    RUN echo "[INFO] Building a debug binary"
    RUN cargo +esp build --target xtensa-esp32-espidf -v
  END

  SAVE ARTIFACT target/xtensa-esp32-espidf/* AS LOCAL artifacts/

flash:
  LOCALLY
  # This step MUST run in "LOCAL" context as you can not yet pass a USB device into a docker container.
  # You MUST have espflash installed localy:
  # https://github.com/esp-rs/espflash

  # Define build arg for the serial port.
  ARG SERIAL_PORT
  # Pass in the name of the binary to flash, most likey to be "artifacts/debug/rust-earthly-build"
  ARG BUILD_BINARY
  
  # Test if we have espflash installed and in our path.
  RUN echo "This step runs localy and needs your machine to have espflash installed first."
  RUN which espflash 2>/dev/null || echo "[ERROR] espflash not found in path, try install it via: cargo install espflash"
  
  # Flash the firmware
  RUN espflash $SERIAL_PORT $BUILD_BINARY

