name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.8
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Docker login # to avoid dockerhub rate-limiting
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Run build
      run: earthly --ci --push --remote-cache=ghcr.io/fristi/project-mycelium:cache +build