name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-submission@v2
        with:
          working-directory: ./backend
      - uses: scalacenter/sbt-dependency-submission@v2
        with:
          working-directory: ./perenual-indexer
      - uses: actions/dependency-review-action@v3